version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: postgres -c 'app.jwt_secret=c744f1ad10af97877d0e9468c3477f9bfb07ef83c5129ef8bef6934e3692f69e'

  postgrest:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: postgrest-container
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@postgres:5432/mydb
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
